nucl_th:

  # For physics topics, use the specific subtopics, e.g. "Astrophysics"
  topic: "Nuclear Theory"
  # An empty list here will include all categories in a topic
  # Use the natural language names of the topics, found here: https://arxiv.org
  # Including more categories will result in more calls to the large language model
  categories: []

  # Relevance score threshold. abstracts that receive a score less than this from the large language model
  # will have their papers filtered out.
  #
  # Must be within 1-10
  threshold: 6

  # A natural language statement that the large language model will use to judge which papers are relevant 
  #
  # For example:
  #     "I am interested in complexity theory papers that establish upper bounds"
  #     "gas chromatography, mass spectrometry"
  #     "making lots of money"
  #
  # This can be empty, which just return a full list of papers with no judgement or filtering,
  # in whatever order arXiv responds with.
  interest: |
    1. I'm interested in energy and momentum loss of high energy jets in ultra-relativistic heavy-ion collisions, which is also called jet quenching.
    2. I would like to keep track with new insights and development within ultra-relativistic heavy-ion physics.

nucl_ex:

  # For physics topics, use the specific subtopics, e.g. "Astrophysics"
  topic: "Nuclear Experiment"
  # An empty list here will include all categories in a topic
  # Use the natural language names of the topics, found here: https://arxiv.org
  # Including more categories will result in more calls to the large language model
  categories: []

  # Relevance score threshold. abstracts that receive a score less than this from the large language model
  # will have their papers filtered out.
  #
  # Must be within 1-10
  threshold: 6

  # A natural language statement that the large language model will use to judge which papers are relevant 
  #
  # For example:
  #     "I am interested in complexity theory papers that establish upper bounds"
  #     "gas chromatography, mass spectrometry"
  #     "making lots of money"
  #
  # This can be empty, which just return a full list of papers with no judgement or filtering,
  # in whatever order arXiv responds with.
  interest: |
    1. I'm interested in energy and momentum loss of high energy jets in ultra-relativistic heavy-ion collisions, which is also called jet quenching.
    2. I would like to keep track with new insights and development within ultra-relativistic heavy-ion physics.

hep_ph:

  # For physics topics, use the specific subtopics, e.g. "Astrophysics"
  topic: "High Energy Physics - Phenomenology"
  # An empty list here will include all categories in a topic
  # Use the natural language names of the topics, found here: https://arxiv.org
  # Including more categories will result in more calls to the large language model
  categories: []

  # Relevance score threshold. abstracts that receive a score less than this from the large language model
  # will have their papers filtered out.
  #
  # Must be within 1-10
  threshold: 6

  # A natural language statement that the large language model will use to judge which papers are relevant 
  #
  # For example:
  #     "I am interested in complexity theory papers that establish upper bounds"
  #     "gas chromatography, mass spectrometry"
  #     "making lots of money"
  #
  # This can be empty, which just return a full list of papers with no judgement or filtering,
  # in whatever order arXiv responds with.
  interest: |
    1. I'm interested in energy and momentum loss of high energy jets in ultra-relativistic heavy-ion collisions, which is also called jet quenching.
    2. I would like to keep track with new insights and development within ultra-relativistic heavy-ion physics.

hep_th:

  # For physics topics, use the specific subtopics, e.g. "Astrophysics"
  topic: "High Energy Physics - Theory"
  # An empty list here will include all categories in a topic
  # Use the natural language names of the topics, found here: https://arxiv.org
  # Including more categories will result in more calls to the large language model
  categories: []

  # Relevance score threshold. abstracts that receive a score less than this from the large language model
  # will have their papers filtered out.
  #
  # Must be within 1-10
  threshold: 6

  # A natural language statement that the large language model will use to judge which papers are relevant 
  #
  # For example:
  #     "I am interested in complexity theory papers that establish upper bounds"
  #     "gas chromatography, mass spectrometry"
  #     "making lots of money"
  #
  # This can be empty, which just return a full list of papers with no judgement or filtering,
  # in whatever order arXiv responds with.
  interest: |
    1. I'm interested in energy and momentum loss of high energy jets in ultra-relativistic heavy-ion collisions, which is also called jet quenching.
    2. I would like to keep track with new insights and development within ultra-relativistic heavy-ion physics.

hep_ex:

  # For physics topics, use the specific subtopics, e.g. "Astrophysics"
  topic: "High Energy Physics - Experiment"
  # An empty list here will include all categories in a topic
  # Use the natural language names of the topics, found here: https://arxiv.org
  # Including more categories will result in more calls to the large language model
  categories: []

  # Relevance score threshold. abstracts that receive a score less than this from the large language model
  # will have their papers filtered out.
  #
  # Must be within 1-10
  threshold: 6

  # A natural language statement that the large language model will use to judge which papers are relevant 
  #
  # For example:
  #     "I am interested in complexity theory papers that establish upper bounds"
  #     "gas chromatography, mass spectrometry"
  #     "making lots of money"
  #
  # This can be empty, which just return a full list of papers with no judgement or filtering,
  # in whatever order arXiv responds with.
  interest: |
    1. I'm interested in energy and momentum loss of high energy jets in ultra-relativistic heavy-ion collisions, which is also called jet quenching.
    2. I would like to keep track with new insights and development within ultra-relativistic heavy-ion physics.

cs:
  # For physics topics, use the specific subtopics, e.g. "Astrophysics"
  topic: "Computer Science"
  # An empty list here will include all categories in a topic
  # Use the natural language names of the topics, found here: https://arxiv.org
  # Including more categories will result in more calls to the large language model
  categories: [ "Artificial Intelligence", "Machine Learning" ]

  # Relevance score threshold. abstracts that receive a score less than this from the large language model
  # will have their papers filtered out.
  #
  # Must be within 1-10
  threshold: 6

  # A natural language statement that the large language model will use to judge which papers are relevant 
  #
  # For example:
  #     "I am interested in complexity theory papers that establish upper bounds"
  #     "gas chromatography, mass spectrometry"
  #     "making lots of money"
  #
  # This can be empty, which just return a full list of papers with no judgement or filtering,
  # in whatever order arXiv responds with.
  interest: |
    1. I'm interested in forecasting time series data.
    2. energy forecasting
    3. demand forecasting

stats:
  # For physics topics, use the specific subtopics, e.g. "Astrophysics"
  topic: "Statistics"
  # An empty list here will include all categories in a topic
  # Use the natural language names of the topics, found here: https://arxiv.org
  # Including more categories will result in more calls to the large language model
  categories: [ "Machine Learning" ]

  # Relevance score threshold. abstracts that receive a score less than this from the large language model
  # will have their papers filtered out.
  #
  # Must be within 1-10
  threshold: 6

  # A natural language statement that the large language model will use to judge which papers are relevant 
  #
  # For example:
  #     "I am interested in complexity theory papers that establish upper bounds"
  #     "gas chromatography, mass spectrometry"
  #     "making lots of money"
  #
  # This can be empty, which just return a full list of papers with no judgement or filtering,
  # in whatever order arXiv responds with.
  interest: |
    1. I'm interested in forecasting time series data.
    2. energy forecasting
    3. demand forecasting
    4. electricity forecasting
